### ISSUE TITLE
Invalid ISO 8601 last_modified in ContentTypes response example

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#12]
The example JSON on the Kentico API site shows a last_modified date as "1. 1. 0001 0:00:00", which fails ISO 8601 DateTime parsing.

Try to reproduce this with the actual API and add support if it's valid.  Otherwise reach out to Kentico to update docs.

**Comment by aweigold** [comment]
Real API doesn't seem to produce this.

**Comment by petrsvihlik** [comment]
@aweigold shall we update the docu? Where exactly did you see it?

**Comment by aweigold** [comment]
The example response here:
https://developer.kenticocloud.com/v1/reference#list-content-types

**Comment by petrsvihlik** [comment]
Submitted to our TWs, they'll fix it soon. 
Btw - you can suggest edits to the documentation by clicking "Suggest edits" link at each chapter. Signing up is open for everyone.

**Comment by petrsvihlik** [comment]
I think we can close this issue now, right?

**Comment by aweigold** [comment]
I'll close it... I knew I could submit it there, but was just not thinking of that... plus my initial reaction was that I was perhaps doing something wrong.  Thanks @petrsvihlik !
