### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#19]
Use SLF4J fascade to not burden users with any particular logging framework.

**Comment by petrsvihlik** [comment]
agreed

**Comment by GaruGaru** [comment]
I'd like to work on this feature, in which components would you like to add logging  ?

**Comment by aweigold** [comment]
I think a good starter would be to log errors when throwing exceptions, and trace logs with timers for hitting the web API and cache.  I would also add debug logs all over the StronglyTypedContentItemConverter.

To add a dependency to SLF4J, you will want to add it to the build.gradle file.  I would do some research on the best version to peg to, as well as if it should be a compile dependency or a provided dependency.  I can certainly help with that research for you as well if needed.

When creating your logger, I typically use the following format in each class:
```
public class BlockquoteInlineContentItemsResolver extends InlineContentItemsResolver<Blockquote> {
  private static final Logger log = LoggerFactory.getLogger(BlockquoteInlineContentItemsResolver.class);

```

Creating your logger by class allows easy configuration for other logging libraries to turn the level up and down for the SDK.

SLF4J is just a fascade, to allow consumers of this to leverage the logging library of their choice, you may need to add an actual logging library to test this and see them.  This could probably be done very easily by adding it as a test dependency.  I would recommend using logback.  If you need help with this configuration, I'm also more then happy to help with that.

**Comment by GaruGaru** [comment]
Thank you for the exhaustive explanation, luckly i've already worked with logback in other projects and i agree that it seems an optimal solution.

>  I would do some research on the best version to peg to, as well as if it should be a compile dependency or a provided dependency.

Reading the [FAQ](https://www.slf4j.org/faq.html)  looks like if the compile scope is the right approach as a library:

> As an author of a library built with Maven, you might want to test your application using a binding, say slf4j-log4j12 or logback-classic, without forcing log4j or logback-classic as a dependency upon your users. This is rather easy to accomplish.
Given that your library's code depends on the SLF4J API, you will need to declare slf4j-api as a compile-time (default scope) dependency.

>  you'll see the log events while running unit tests. 

Regarding the testing step do you think that is worth to write some unit test for critical operation logging ? It should be doable using mockito.

**Comment by aweigold** [comment]
IMHO I have seen many unit tests that have used mockito (or another mocking library) to test logging, and they all have turned to garbage over time.  I would avoid adding tests for logging unless we have some sort of custom logging level/event.  That said, I would understand the sentiment to add a unit test for new features.  I'll let you make an educated decision on what you want to do with it.

**Comment by aweigold** [comment]
Thanks for the help @GaruGaru !!!!
