### ISSUE TITLE
Provide DeliveryParameterBuilder.language(Locale language) method

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#28]
The parameter builder expects a string showing a Locale represented as "es-ES", build in support to allow a standard Java Locale to be passed in and perform conversion automatically.

**Comment by cunhazera** [comment]
@aweigold is there someone working on it?

**Comment by aweigold** [comment]
@cunhazera I can get it in today... easy task

**Comment by cunhazera** [comment]
@aweigold can you check the pull request referenced here?
I could not solve that build problem

**Comment by aweigold** [comment]
@cunhazera I just saw the PR after I already commented.  I'm looking at the build issue right now.  There are some encrypted passwords/keys for deployment that travis does not expose in PR builds, it looks like I didn't condition to not try deploys on PRs.

**Comment by cunhazera** [comment]
Ok, I wait for your response.
And please let me know if anything in the PR is not as you expected.

**Comment by cunhazera** [comment]
@aweigold I think that the issue can be closed now, right?

**Comment by aweigold** [comment]
@cunhazera yes it can, I'll close it now.  Good work.
