### ISSUE TITLE
Shadow Joda or another library to implement JSR-310 time dependencies

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#35]
Currently the Java SDK uses Java 8 ZonedDateTime objects.  This depends on Duration which doesn't exist in the Android API until version 26 (which less than 1% of devices are on).

Explore adding Joda or another library into the shadow jar created for Android to provide the JSR-310 java.time API and identify the lowest Android API compatible with it.  If the API compatibility is still > 19, create a new issue identifying the new barrier.

**Comment by luan-cestari** [comment]
Hi, I created a PR #42 for to change asked.  There is https://github.com/dlew/joda-time-android which seems better for android but for SDK it would require the client of SDK to set Joda in the Application onCreate method, so I choose the original Joda dependency

**Comment by aweigold** [comment]
I commented on the PR.  I'll also update the description of this ticket based on our findings.  Thanks for the help!

**Comment by aweigold** [comment]
Per internal conversations... we are going to be abandoning the effort to make this API android compatible in lieu of a separate library that has been developed.  Closing this issue.
