### ISSUE TITLE
Create a general RichText transformer (similar to link resolver)

### ISSUE THREAD

**Issue by jordangerads** [Kentico/delivery-sdk-java#36]

**Comment by petrsvihlik** [comment]
Similarly to:
 - .NET SDK - [code](https://github.com/Kentico/delivery-sdk-net/tree/master/KenticoCloud.Delivery/InlineContentItems) + [documentation](https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering)


DoD:
- unit (and/or e2e) tests
- documentation (code examples in the readme or dedicated gh wiki page)

**Comment by aweigold** [comment]
I have the heart of what's needed for this complete now... and will merge to master shortly.  This will be available in 1.0.5-SNAPSHOT

As far as using structured content, I will either implement something that will scan the classpath for JSoup to do this, or write up a wiki explaining how to use JSoup for this, as not to handcuff consumers to that library.
