### ISSUE TITLE
Add ViewResolver/Rendering Interface

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#37]
It may not be immediately clear to consumers of the SDK how to link their InlineContentItemsResolver to their View Rendering library of choice.  Provide an interface that can abstract the implementation to allow choice for consumers.

Furthermore add a Thymeleaf implementation that will check the classpath first for the dependency, and if it exists run the engine, but do not make it a required dependency to use the SDK.

This would work similar to how Spring Boot autoconfigures ViewResolvers based on what is on the classpath.

**Comment by aweigold** [comment]
For information on making compile only dependencies, see this: https://blog.gradle.org/introducing-compile-only-dependencies

**Comment by aweigold** [comment]
Closing this issue.  @petrsvihlik I'll work on the wiki for this hopefully sometime this week, and release a 1.0.5 release.  With this issue complete, if the [Thymeleaf library](http://www.thymeleaf.org/) is on the classpath, it will automatically look for html fragment templates named the same as a content type codename, and resolve them for you (allowing html to be separate from code, unlike the existing InlineContentItemResolvers).  I've been doing something similar for awhile on our internal app, but generalized it so a consumer could potentially implement an engine for another templating library.

**Comment by petrsvihlik** [comment]
Sounds great! It seems like an analogy to: https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering right?

**Comment by aweigold** [comment]
Correct, it is analogous to to the .Net MVC portion, but not the structured rich text element itself.
