### ISSUE TITLE
Strongly typed nested modular items

### ISSUE THREAD

**Issue by Enngage** [Kentico/delivery-sdk-java#41]
Hey, 

I was going through the code and it seems that modular items nested within a strongly typed class can be only of generic `ContentItem ` item. This can be seen for example with the 'relatedArticles' property in this [sample class](https://github.com/Kentico/delivery-sdk-java/blob/master/src/test/java/com/kenticocloud/delivery/ArticleItem.java).

It would be nice so that you could define strongly typed classes within a class and let SDK handle conversion for you. Something like this is implemented in our TypeScript SDK ([example](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#nesting-modular-content)).

**Comment by aweigold** [comment]
Hi,

Unless there is a false positive in the `DeliveryClientTest` class, take a look at `testGetStronglyTypedItem()`.  You'll see that we test against the implicit binding against `List<ArticleItem> articleItems`.  This should work with an explicit annotation as well.

That said, if you are using the code generators, there is not enough information in the typing API to make these assertions, so generated code will always be `ContentItem`, but manually defined strongly typed classes will work.

If you find the test is a false positive, let me know.  I'll keep this issue open a few days for validation.

**Comment by Enngage** [comment]
Thanks for the response! I'm not sure I see such a test in `testGetStronglyTypedItem ` that would test if the 'related_articles' items are indeed of `ArticleItem` type.

My goal would be to verify that you can replace

```
   @ContentItemMapping("related_articles")
    List<ContentItem> relatedArticles;
```

with 

```
   @ContentItemMapping("related_articles")
    List<ArticleItem> relatedArticles;
```

and get the `ArticleItem `typed objects and be able to further traverse through the modular content items.

If thats how it works, then feel free to close the issue :-)

**Comment by aweigold** [comment]
The SDK will implicitly map `relatedArticles` to `related_articles`, the annotation is optional.  Adding the annotation is perfectly acceptable.

**Comment by Enngage** [comment]
I'm not talking about annotations, see the examples above. What I mean is that I as a developer might want to access modular content that is embedded within an item in a strongly typed manner. 

Suppose I have types `Blog `and `Post`. In `Blog` post type I would like to define property `posts` that will contain **strongly typed** objects of `Post` type:

```
@ContentItemMapping("blog")
public class Blog{

   @ContentItemMapping("posts")
    List<Post> posts;
}

@ContentItemMapping("post")
public class Post{

    @ElementMapping("text")
    String text;
}
```
Now, if I query for `Blog` item, I expect that the `posts` property will contain a list of `Post` objects so that I can then easily access `text` property which is known and property mapped from the modular content that is part of the response. Otherwise I would have to load the item from the modular content manually and also manually retrieve the item property.

**Comment by aweigold** [comment]
I think there is some confusion here.  Let me try to address it better.

Mapping elements and modular content can be done implicitly by the field name, or explicitly by the annotation.  The unit test I referenced at the beginning does this implicitly, as there is no annotation.  That said however, the strongly typed modular content is injected, showing support for this.

Feel free to make a mapping to a strongly typed modular content item, it should work, based on the unit test, with or without the annotation.  If you find that it does not work, let me know.

I'll keep this issue open for validation.

**Comment by Enngage** [comment]
Yeah, I think there is :) I setup following scenario:

```
@ContentItemMapping("article")
public class ArticleTest {

    public ArticleTest(){}

    @ElementMapping("title")
    public String title;

    @ContentItemMapping("related_articles")
    public List<ArticleTest> relatedArticles;

    public void setTitle(String title){
        this.title = title;
    }

    public String getTitle(){
        return this.title;
    }

    public void setRelatedArticles(List<ArticleTest> items){
        this.relatedArticles = items;
    }

    public List<ArticleTest> getRelatedArticles(){
        return this.relatedArticles;
    }
}
```
And then used it like:

```
DeliveryClient client = new DeliveryClient("683771be-aa26-4887-b1b6-482f56418ffd");
        client.registerType("article", ArticleTest.class);

        try {
            Object model = client.getItem("on_roasts", ArticleTest.class);

            // article is indeed of ArticleTest type
            ArticleTest article = (ArticleTest)model;

            // all good here
            String title = article.getTitle();

            // this throws Exception, but works if I use ContentItem
            // it would make sense for developers to be able to traverse the modular
            // items in a strongly typed manner
            List<ArticleTest> relatedArticles = article.getRelatedArticles();
```

The point is that you should be able to use `ArticleTest` as a property instead of the generic `ContentItem`. Does it make sense now? :)

**Comment by aweigold** [comment]
Running the code, I am getting an NPE, but not from the getRelatedArticles() line, but while the SDK is recursively adding relatedArticles to children.  I can work on a fix.

**Comment by aweigold** [comment]
Thanks for finding the issue @Enngage .  As I mentioned, this wasn't an issue with the StronglyTyped modular content, but an NPE when nesting the same type of modular content recursively.  I committed a fix, if you would like to use it, it's in the SNAPSHOT build, which you can use in the following fashion:
```
repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
    compile('com.kenticocloud:delivery-sdk-java:1.0.6-SNAPSHOT')
}
```
