### ISSUE TITLE
Using inline content items that contain dollar signs will cause java.util.regex.Matcher to throw java.lang.IndexOutOfBoundsException: No group #

### ISSUE THREAD

**Issue by bitskeptic-tc** [Kentico/delivery-sdk-java#49]
The matcher.appendReplacement method on line 202 of com.kenticocloud.delivery.RichTextElementConverter that places inline content item html inside parent content item html will interpret dollar signs (and their trailing numbers) as capturing groups in the matcher's pattern. If the interpreted capturing group does not exist in the Matcher object, java.lang.IndexOutOfBoundsException: No group # is thrown. The dollar signs in replacement strings should be escaped to avoid this behavior. See https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#appendReplacement(java.lang.StringBuffer,%20java.lang.String)

**Comment by aweigold** [comment]
Good find @bitskeptic-tc !

I'll work with you on getting a PR done for this, could we add a unit test to cover the scenario?

**Comment by aweigold** [comment]
PR is squashed and merged.  Closing this issue.
