### ISSUE TITLE
Implement optional retry logic for CDN failures

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#53]
@petrsvihlik I'll implement this as we discussed, but if you have any requirements around this, feel free to comment on this issue.

**Comment by petrsvihlik** [comment]
@JanLenoch is currently researching the best approach for the retry policy in the .NET SDK. I'll ask him to do the review of your PR. (we may take over your implementation for the .NET SDK if it aligns with what @JanLenoch will come up with).
