### ISSUE TITLE
Missing Secure access support in the Readme

### ISSUE THREAD

**Issue by MartinaFarkasova** [Kentico/delivery-sdk-java#58]
I would like to address that we support secure access in our feature matrix on DevHub: 
https://developer.kenticocloud.com/v1/docs/delivery-sdks

Please add this information to the Readme file.

**Comment by aweigold** [comment]
This has been updated.  Closing issue.

**Comment by MartinaFarkasova** [comment]
Thanks, Adam! I updated the docs on DevHub: https://developer.kenticocloud.com/v1/docs/javaandroid#section-supported-features
