### ISSUE TITLE
Page.nextPage() fails with NPE

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#59]
The `DeliveryClient` does not set the `stronglyTypedContentItemConverter` on the `ContentItemsListingResponse` on calls to `getPageOfItems` and `getNextPage` causing the constructor of the new `Page` to throw an NPE when it invokes to `response.castTo(tClass)`.

**Comment by Krishan-Sharma** [comment]
Hi,

Looking to contribute to this project. Can someone please assign this issue to me?

Thanks,
Krishan

**Comment by petrsvihlik** [comment]
Hi @Krishan-Sharma, we appreciate that! Please accept the collaborator invitation I've just sent you and I'll be able to assign the issue to you :)

**Comment by Krishan-Sharma** [comment]
Thanks, @petrsvihlik. I have accepted the invitation. I am contributing to OSS for the first time. Would there be some documentation other than the code of conduct that I can follow for contributing to this project and if yes, can you please help me with that?

Thanks,
Krishan

**Comment by aweigold** [comment]
This has been fixed in 2.0.0-SNAPSHOT.  Closing issue.
