### ISSUE TITLE
Rename modular content to linked items

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-java#69]
Based on our vision regarding content items, we have to rename "Modular content element" to "Linked items element". From the Delivery SDK's point of view, it means that we are going to rename everything that contains "modularContent" to "linkedItems".

Checklist:
- [ ] updated all members (methods/properties/classes/...)
- [ ] updated .MD files
- [ ] updated tests
- [ ] updated github wiki

Keep in mind, that the Delivery API responses will remain the same. They'll still contain "modular_content".

Example implementation: https://github.com/Kentico/delivery-sdk-net/pull/130

Notes:
- this will result in a breaking change because of changes in public members -> [major version number has to be increased](https://semver.org/)
- plan your release so that the changes go live on 2018-10-03 and onwards.

**Comment by kcnklub** [comment]
So this is just a simple refactor of a class?

**Comment by shawnrc** [comment]
There's a number of classes and docstrings that mention modular content as well. In [certain docstrings](https://github.com/Kentico/delivery-sdk-java/blob/fc1b25f5e6df9861f1de5abaf9d7a60f7673466f/delivery/src/main/java/com/kenticocloud/delivery/ContentItemResponse.java#L68) there are links to reference docs that explicitly mention "modular content" - is this also going to be renamed to linked items?

**Comment by shawnrc** [comment]
@petrpyszko Makes sense - can I just assume links like `https://developer.kenticocloud.com/v1/reference#modular-content` will get transposed to `https://developer.kenticocloud.com/v2/reference#linked-items` to reflect the major version number increase and name change?

**Comment by petrsvihlik** [comment]
@shawnrc  yes

**Comment by shawnrc** [comment]
Howdy! PR #72 Should take care of all the code mentions of modular content, we'd just need to update the wiki afterward.
