### ISSUE TITLE
Update Jackson configuration to ignore unknown fields

### ISSUE THREAD

**Issue by aweigold** [Kentico/delivery-sdk-java#78]
### Motivation

Issues like #77 and #73 are demonstrating that strict validation of responses in deserialization is problematic and can cause breaking changes for consumers.

### Proposed solution

Configure the Jackson ObjectMapper to not fail on unknown properties and types.

### Additional context

The `ObjectMapper` has a `configure` method which can be leveraged to adjust features of Jackson's behavior.  See the [DeserializationFeature](https://fasterxml.github.io/jackson-databind/javadoc/2.0.0/com/fasterxml/jackson/databind/DeserializationFeature.html) for reference to related items.

**Comment by aweigold** [comment]
Unit tests should also be included to prove deserialization with both unknown types and unknown properties.

**Comment by aweigold** [comment]
This is completed in the 2.0 branch... needs to be merged into master.

**Comment by MrJINXIN** [comment]
hello,
I had the same problem.Please, how do I write the Jackson configuration file for the ignore attribute

**Comment by aweigold** [comment]
Hi @MrJINXIN .  This was fixed with the 2.0.3 release of the SDK.
